server:
  port: 8888
  servlet:
    context-path: /demo

spring:
  # 配置Thymeleaf模板
  thymeleaf:
    cache: false                      # 是否有模板缓存
    prefix: classpath:/templates/     # 模板放置的位置
    suffix: .html                     # 模板后缀
    mode: HTML                        # 模板类型
    encoding: UTF-8                   # 模板编码


